language: php

sudo: false

php:
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run
    - ./vendor/bin/phpstan analyse --level=7 lib
    - ./vendor/bin/phpunit --exclude-group=tmux
    - tmux new -s maestro-test "./vendor/bin/phpunit --group=tmux"
